### PR TITLE
Updated to class interface. Closes #27.

### LINKED ISSUE #27: Update to new interface
This should just send events to upstream servers. No filtering anymore. Needs to implement the stop interface to try to drain anything left in the queue during shutdown.

### PR DESCRIPTION
**Pull request by arb**
I also removed the `mapEvents` logic because that seemed more like domain specific logic that could be handled in a app specific transform stream.

### CODE REVIEW

**Comment by arb** [comment]
@kevinmstephens since you seem like the only person who uses this, do you want to weigh in on any changes here?

**Comment by kevinmstephens** [comment]
I'm not the only one! haha.

So filtering is now setup within good but outside of the reporter using squeeze if I understand correctly. And the `stop` implementation looks good.

Thanks for the updates!

**Comment by arb** [comment]
Right. I also removed the mapping feature where it grouped events by the event type to make it more use agnostic. Now it's just a generic write stream and can be used anywhere a write stream is supported.

**Comment by kevinmstephens** [comment]
That also looks good. :+1:

**Pull request closed without merging**
